const filteredMonsterList = [
  {
    index: "aboleth",
    name: "Aboleth",
    url: "/api/2014/monsters/aboleth",
    image: "/api/2014/images/monsters/aboleth.png",
  },
  {
    index: "acolyte",
    name: "Acolyte",
    url: "/api/2014/monsters/acolyte",
    image: "/api/2014/images/monsters/acolyte.png",
  },
  {
    index: "adult-black-dragon",
    name: "Adult Black Dragon",
    url: "/api/2014/monsters/adult-black-dragon",
    image: "/api/2014/images/monsters/adult-black-dragon.png",
  },
  {
    index: "adult-blue-dragon",
    name: "Adult Blue Dragon",
    url: "/api/2014/monsters/adult-blue-dragon",
    image: "/api/2014/images/monsters/adult-blue-dragon.png",
  },
  {
    index: "adult-brass-dragon",
    name: "Adult Brass Dragon",
    url: "/api/2014/monsters/adult-brass-dragon",
    image: "/api/2014/images/monsters/adult-brass-dragon.png",
  },
  {
    index: "adult-bronze-dragon",
    name: "Adult Bronze Dragon",
    url: "/api/2014/monsters/adult-bronze-dragon",
    image: "/api/2014/images/monsters/adult-bronze-dragon.png",
  },
  {
    index: "adult-copper-dragon",
    name: "Adult Copper Dragon",
    url: "/api/2014/monsters/adult-copper-dragon",
    image: "/api/2014/images/monsters/adult-copper-dragon.png",
  },
  {
    index: "adult-gold-dragon",
    name: "Adult Gold Dragon",
    url: "/api/2014/monsters/adult-gold-dragon",
    image: "/api/2014/images/monsters/adult-gold-dragon.png",
  },
  {
    index: "adult-green-dragon",
    name: "Adult Green Dragon",
    url: "/api/2014/monsters/adult-green-dragon",
    image: "/api/2014/images/monsters/adult-green-dragon.png",
  },
  {
    index: "adult-red-dragon",
    name: "Adult Red Dragon",
    url: "/api/2014/monsters/adult-red-dragon",
    image: "/api/2014/images/monsters/adult-red-dragon.png",
  },
  {
    index: "adult-silver-dragon",
    name: "Adult Silver Dragon",
    url: "/api/2014/monsters/adult-silver-dragon",
    image: "/api/2014/images/monsters/adult-silver-dragon.png",
  },
  {
    index: "adult-white-dragon",
    name: "Adult White Dragon",
    url: "/api/2014/monsters/adult-white-dragon",
    image: "/api/2014/images/monsters/adult-white-dragon.png",
  },
  {
    index: "air-elemental",
    name: "Air Elemental",
    url: "/api/2014/monsters/air-elemental",
    image: "/api/2014/images/monsters/air-elemental.png",
  },
  {
    index: "ancient-black-dragon",
    name: "Ancient Black Dragon",
    url: "/api/2014/monsters/ancient-black-dragon",
    image: "/api/2014/images/monsters/ancient-black-dragon.png",
  },
  {
    index: "ancient-blue-dragon",
    name: "Ancient Blue Dragon",
    url: "/api/2014/monsters/ancient-blue-dragon",
    image: "/api/2014/images/monsters/ancient-blue-dragon.png",
  },
  {
    index: "ancient-brass-dragon",
    name: "Ancient Brass Dragon",
    url: "/api/2014/monsters/ancient-brass-dragon",
    image: "/api/2014/images/monsters/ancient-brass-dragon.png",
  },
  {
    index: "ancient-bronze-dragon",
    name: "Ancient Bronze Dragon",
    url: "/api/2014/monsters/ancient-bronze-dragon",
    image: "/api/2014/images/monsters/ancient-bronze-dragon.png",
  },
  {
    index: "ancient-copper-dragon",
    name: "Ancient Copper Dragon",
    url: "/api/2014/monsters/ancient-copper-dragon",
    image: "/api/2014/images/monsters/ancient-copper-dragon.png",
  },
  {
    index: "ancient-gold-dragon",
    name: "Ancient Gold Dragon",
    url: "/api/2014/monsters/ancient-gold-dragon",
    image: "/api/2014/images/monsters/ancient-gold-dragon.png",
  },
  {
    index: "ancient-green-dragon",
    name: "Ancient Green Dragon",
    url: "/api/2014/monsters/ancient-green-dragon",
    image: "/api/2014/images/monsters/ancient-green-dragon.png",
  },
  {
    index: "ancient-red-dragon",
    name: "Ancient Red Dragon",
    url: "/api/2014/monsters/ancient-red-dragon",
    image: "/api/2014/images/monsters/ancient-red-dragon.png",
  },
  {
    index: "ancient-silver-dragon",
    name: "Ancient Silver Dragon",
    url: "/api/2014/monsters/ancient-silver-dragon",
    image: "/api/2014/images/monsters/ancient-silver-dragon.png",
  },
  {
    index: "ancient-white-dragon",
    name: "Ancient White Dragon",
    url: "/api/2014/monsters/ancient-white-dragon",
    image: "/api/2014/images/monsters/ancient-white-dragon.png",
  },
  {
    index: "androsphinx",
    name: "Androsphinx",
    url: "/api/2014/monsters/androsphinx",
    image: "/api/2014/images/monsters/androsphinx.png",
  },
  {
    index: "animated-armor",
    name: "Animated Armor",
    url: "/api/2014/monsters/animated-armor",
    image: "/api/2014/images/monsters/animated-armor.png",
  },
  {
    index: "ankheg",
    name: "Ankheg",
    url: "/api/2014/monsters/ankheg",
    image: "/api/2014/images/monsters/ankheg.png",
  },
  {
    index: "ape",
    name: "Ape",
    url: "/api/2014/monsters/ape",
    image: "/api/2014/images/monsters/ape.png",
  },
  {
    index: "archmage",
    name: "Archmage",
    url: "/api/2014/monsters/archmage",
    image: "/api/2014/images/monsters/archmage.png",
  },
  {
    index: "assassin",
    name: "Assassin",
    url: "/api/2014/monsters/assassin",
    image: "/api/2014/images/monsters/assassin.png",
  },
  {
    index: "awakened-shrub",
    name: "Awakened Shrub",
    url: "/api/2014/monsters/awakened-shrub",
    image: "/api/2014/images/monsters/awakened-shrub.png",
  },
  {
    index: "awakened-tree",
    name: "Awakened Tree",
    url: "/api/2014/monsters/awakened-tree",
    image: "/api/2014/images/monsters/awakened-tree.png",
  },
  {
    index: "axe-beak",
    name: "Axe Beak",
    url: "/api/2014/monsters/axe-beak",
    image: "/api/2014/images/monsters/axe-beak.png",
  },
  {
    index: "baboon",
    name: "Baboon",
    url: "/api/2014/monsters/baboon",
    image: "/api/2014/images/monsters/baboon.png",
  },
  {
    index: "badger",
    name: "Badger",
    url: "/api/2014/monsters/badger",
    image: "/api/2014/images/monsters/badger.png",
  },
  {
    index: "balor",
    name: "Balor",
    url: "/api/2014/monsters/balor",
    image: "/api/2014/images/monsters/balor.png",
  },
  {
    index: "bandit",
    name: "Bandit",
    url: "/api/2014/monsters/bandit",
    image: "/api/2014/images/monsters/bandit.png",
  },
  {
    index: "bandit-captain",
    name: "Bandit Captain",
    url: "/api/2014/monsters/bandit-captain",
    image: "/api/2014/images/monsters/bandit-captain.png",
  },
  {
    index: "barbed-devil",
    name: "Barbed Devil",
    url: "/api/2014/monsters/barbed-devil",
    image: "/api/2014/images/monsters/barbed-devil.png",
  },
  {
    index: "black-bear",
    name: "Black Bear",
    url: "/api/2014/monsters/black-bear",
    image: "/api/2014/images/monsters/black-bear.png",
  },
  {
    index: "black-dragon-wyrmling",
    name: "Black Dragon Wyrmling",
    url: "/api/2014/monsters/black-dragon-wyrmling",
    image: "/api/2014/images/monsters/black-dragon-wyrmling.png",
  },
  {
    index: "black-pudding",
    name: "Black Pudding",
    url: "/api/2014/monsters/black-pudding",
    image: "/api/2014/images/monsters/black-pudding.png",
  },
  {
    index: "blink-dog",
    name: "Blink Dog",
    url: "/api/2014/monsters/blink-dog",
    image: "/api/2014/images/monsters/blink-dog.png",
  },
  {
    index: "blood-hawk",
    name: "Blood Hawk",
    url: "/api/2014/monsters/blood-hawk",
    image: "/api/2014/images/monsters/blood-hawk.png",
  },
  {
    index: "blue-dragon-wyrmling",
    name: "Blue Dragon Wyrmling",
    url: "/api/2014/monsters/blue-dragon-wyrmling",
    image: "/api/2014/images/monsters/blue-dragon-wyrmling.png",
  },
  {
    index: "boar",
    name: "Boar",
    url: "/api/2014/monsters/boar",
    image: "/api/2014/images/monsters/boar.png",
  },
  {
    index: "bone-devil",
    name: "Bone Devil",
    url: "/api/2014/monsters/bone-devil",
    image: "/api/2014/images/monsters/bone-devil.png",
  },
  {
    index: "brass-dragon-wyrmling",
    name: "Brass Dragon Wyrmling",
    url: "/api/2014/monsters/brass-dragon-wyrmling",
    image: "/api/2014/images/monsters/brass-dragon-wyrmling.png",
  },
  {
    index: "bronze-dragon-wyrmling",
    name: "Bronze Dragon Wyrmling",
    url: "/api/2014/monsters/bronze-dragon-wyrmling",
    image: "/api/2014/images/monsters/bronze-dragon-wyrmling.png",
  },
  {
    index: "brown-bear",
    name: "Brown Bear",
    url: "/api/2014/monsters/brown-bear",
    image: "/api/2014/images/monsters/brown-bear.png",
  },
  {
    index: "bugbear",
    name: "Bugbear",
    url: "/api/2014/monsters/bugbear",
    image: "/api/2014/images/monsters/bugbear.png",
  },
  {
    index: "camel",
    name: "Camel",
    url: "/api/2014/monsters/camel",
    image: "/api/2014/images/monsters/camel.png",
  },
  {
    index: "chain-devil",
    name: "Chain Devil",
    url: "/api/2014/monsters/chain-devil",
    image: "/api/2014/images/monsters/chain-devil.png",
  },
  {
    index: "clay-golem",
    name: "Clay Golem",
    url: "/api/2014/monsters/clay-golem",
    image: "/api/2014/images/monsters/clay-golem.png",
  },
  {
    index: "cockatrice",
    name: "Cockatrice",
    url: "/api/2014/monsters/cockatrice",
    image: "/api/2014/images/monsters/cockatrice.png",
  },
  {
    index: "commoner",
    name: "Commoner",
    url: "/api/2014/monsters/commoner",
    image: "/api/2014/images/monsters/commoner.png",
  },
  {
    index: "constrictor-snake",
    name: "Constrictor Snake",
    url: "/api/2014/monsters/constrictor-snake",
    image: "/api/2014/images/monsters/constrictor-snake.png",
  },
  {
    index: "crocodile",
    name: "Crocodile",
    url: "/api/2014/monsters/crocodile",
    image: "/api/2014/images/monsters/crocodile.png",
  },
  {
    index: "dryad",
    name: "Dryad",
    url: "/api/2014/monsters/dryad",
    image: "/api/2014/images/monsters/dryad.png",
  },
  {
    index: "earth-elemental",
    name: "Earth Elemental",
    url: "/api/2014/monsters/earth-elemental",
    image: "/api/2014/images/monsters/earth-elemental.png",
  },
  {
    index: "goblin",
    name: "Goblin",
    url: "/api/2014/monsters/goblin",
    image: "/api/2014/images/monsters/goblin.png",
  },
  {
    index: "mimic",
    name: "Mimic",
    url: "/api/2014/monsters/mimic",
    image: "/api/2014/images/monsters/mimic.png",
  },
  {
    index: "warhorse",
    name: "Warhorse",
    url: "/api/2014/monsters/warhorse",
    image: "/api/2014/images/monsters/warhorse.png",
  },
  {
    index: "water-elemental",
    name: "Water Elemental",
    url: "/api/2014/monsters/water-elemental",
    image: "/api/2014/images/monsters/water-elemental.png",
  },
  {
    index: "weasel",
    name: "Weasel",
    url: "/api/2014/monsters/weasel",
    image: "/api/2014/images/monsters/weasel.png",
  },
  {
    index: "wight",
    name: "Wight",
    url: "/api/2014/monsters/wight",
    image: "/api/2014/images/monsters/wight.png",
  },
  {
    index: "will-o-wisp",
    name: "Will-o'-Wisp",
    url: "/api/2014/monsters/will-o-wisp",
    image: "/api/2014/images/monsters/will-o-wisp.png",
  },
  {
    index: "winter-wolf",
    name: "Winter Wolf",
    url: "/api/2014/monsters/winter-wolf",
    image: "/api/2014/images/monsters/winter-wolf.png",
  },
  {
    index: "wolf",
    name: "Wolf",
    url: "/api/2014/monsters/wolf",
    image: "/api/2014/images/monsters/wolf.png",
  },
  {
    index: "worg",
    name: "Worg",
    url: "/api/2014/monsters/worg",
    image: "/api/2014/images/monsters/worg.png",
  },
  {
    index: "wraith",
    name: "Wraith",
    url: "/api/2014/monsters/wraith",
    image: "/api/2014/images/monsters/wraith.png",
  },
  {
    index: "xorn",
    name: "Xorn",
    url: "/api/2014/monsters/xorn",
    image: "/api/2014/images/monsters/xorn.png",
  },
  {
    index: "young-black-dragon",
    name: "Young Black Dragon",
    url: "/api/2014/monsters/young-black-dragon",
    image: "/api/2014/images/monsters/young-black-dragon.png",
  },
  {
    index: "young-blue-dragon",
    name: "Young Blue Dragon",
    url: "/api/2014/monsters/young-blue-dragon",
    image: "/api/2014/images/monsters/young-blue-dragon.png",
  },
  {
    index: "young-brass-dragon",
    name: "Young Brass Dragon",
    url: "/api/2014/monsters/young-brass-dragon",
    image: "/api/2014/images/monsters/young-brass-dragon.png",
  },
  {
    index: "young-bronze-dragon",
    name: "Young Bronze Dragon",
    url: "/api/2014/monsters/young-bronze-dragon",
    image: "/api/2014/images/monsters/young-bronze-dragon.png",
  },
  {
    index: "young-copper-dragon",
    name: "Young Copper Dragon",
    url: "/api/2014/monsters/young-copper-dragon",
    image: "/api/2014/images/monsters/young-copper-dragon.png",
  },
  {
    index: "young-gold-dragon",
    name: "Young Gold Dragon",
    url: "/api/2014/monsters/young-gold-dragon",
    image: "/api/2014/images/monsters/young-gold-dragon.png",
  },
  {
    index: "young-green-dragon",
    name: "Young Green Dragon",
    url: "/api/2014/monsters/young-green-dragon",
    image: "/api/2014/images/monsters/young-green-dragon.png",
  },
  {
    index: "young-red-dragon",
    name: "Young Red Dragon",
    url: "/api/2014/monsters/young-red-dragon",
    image: "/api/2014/images/monsters/young-red-dragon.png",
  },
  {
    index: "young-silver-dragon",
    name: "Young Silver Dragon",
    url: "/api/2014/monsters/young-silver-dragon",
    image: "/api/2014/images/monsters/young-silver-dragon.png",
  },
  {
    index: "young-white-dragon",
    name: "Young White Dragon",
    url: "/api/2014/monsters/young-white-dragon",
    image: "/api/2014/images/monsters/young-white-dragon.png",
  },
  {
    index: "zombie",
    name: "Zombie",
    url: "/api/2014/monsters/zombie",
    image: "/api/2014/images/monsters/zombie.png",
  },
];
export default filteredMonsterList;
